language: go
dist: bionic
go:
  - "1.11"
  - "1.12"
  - "1.13"
  - "1.14"
  - "1.15"
  - master
os:
  - linux
  - osx
  - windows
jobs:
  allow_failures:
    - go: master
  fast_finish: true
script:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - go test -v -covermode=count -coverprofile=coverage.out
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
